server:
  port: 8090
  servlet:
    context-path: /boss
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbboss?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true













